#!/usr/bin/env python3
"""
Notification Handler
Sends job alerts via email (Gmail) or Discord webhook
"""

import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import os
import requests

def send_email_notification(new_jobs):
    """
    Send HTML email via Gmail SMTP
    Requires Gmail App Password (not regular password)
    Setup: https://myaccount.google.com/apppasswords
    """
    
    sender = os.getenv('GMAIL_USER')
    password = os.getenv('GMAIL_APP_PASSWORD')
    recipient = os.getenv('NOTIFY_EMAIL')
    
    if not all([sender, password, recipient]):
        print("   ⚠ Email credentials not configured")
        return
    
    subject = f"🎯 {len(new_jobs)} New Grants Jobs Found"
    
    # Build HTML email
    html = f"""
    <html>
    <head>
        <style>
            body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; }}
            .header {{ background: #0066cc; color: white; padding: 20px; }}
            .job {{ border-left: 4px solid #0066cc; padding: 15px; margin: 20px 0; background: #f9f9f9; }}
            .job h3 {{ margin: 0 0 10px 0; color: #0066cc; }}
            .job-meta {{ color: #666; font-size: 14px; }}
            .job-link {{ display: inline-block; margin-top: 10px; padding: 8px 16px; background: #0066cc; color: white; text-decoration: none; border-radius: 4px; }}
            .footer {{ margin-top: 30px; padding-top: 20px; border-top: 1px solid #ddd; color: #666; font-size: 12px; }}
        </style>
    </head>
    <body>
        <div class="header">
            <h1>🎯 New Grants Management Opportunities</h1>
            <p>{len(new_jobs)} new positions found</p>
        </div>
    """
    
    # Group jobs by source
    by_source = {}
    for job in new_jobs:
        source = job['source']
        if source not in by_source:
            by_source[source] = []
        by_source[source].append(job)
    
    # Add jobs to email
    for source, jobs in by_source.items():
        html += f"<h2 style='margin-top: 30px; color: #0066cc;'>📌 {source} ({len(jobs)} jobs)</h2>"
        
        for job in jobs[:20]:  # Limit to prevent huge emails
            html += f"""
            <div class="job">
                <h3>{job['title']}</h3>
                <p class="job-meta">
                    <strong>{job['agency']}</strong><br>
                    📍 {job['location']}<br>
                    💰 {job['salary']}<br>
                    📅 Posted: {job.get('posted', 'Recently')}
                </p>
                <a href="{job['url']}" class="job-link">View Job →</a>
            </div>
            """
    
    if len(new_jobs) > 60:
        html += f"<p><em>...and {len(new_jobs) - 60} more jobs (check your repo for full list)</em></p>"
    
    html += """
        <div class="footer">
            <p>This alert was generated by your Grants Job Monitor.<br>
            Powered by GitHub Actions • Running on schedule • 100% free</p>
        </div>
    </body>
    </html>
    """
    
    # Create message
    msg = MIMEMultipart('alternative')
    msg['Subject'] = subject
    msg['From'] = sender
    msg['To'] = recipient
    
    msg.attach(MIMEText(html, 'html'))
    
    # Send email
    try:
        with smtplib.SMTP_SSL('smtp.gmail.com', 465) as server:
            server.login(sender, password)
            server.send_message(msg)
        print(f"   ✓ Email sent to {recipient}")
    except Exception as e:
        print(f"   ❌ Email error: {e}")
        raise

def send_discord_notification(new_jobs):
    """
    Send notification to Discord webhook
    Setup: Server Settings → Integrations → Webhooks → New Webhook
    """
    
    webhook_url = os.getenv('DISCORD_WEBHOOK')
    
    if not webhook_url:
        # Not an error - Discord is optional
        return
    
    # Discord has 2000 char limit per message, so we'll split if needed
    chunks = []
    current_chunk = f"**🎯 {len(new_jobs)} New Grants Jobs Found**\n\n"
    
    for job in new_jobs[:20]:  # Limit to 20 jobs
        job_text = f"**{job['title']}**\n"
        job_text += f"{job['agency']} | {job['location']}\n"
        job_text += f"💰 {job['salary']} | 📅 {job.get('posted', 'Recently')}\n"
        job_text += f"{job['url']}\n\n"
        
        # Check if adding this job would exceed limit
        if len(current_chunk) + len(job_text) > 1900:
            chunks.append(current_chunk)
            current_chunk = job_text
        else:
            current_chunk += job_text
    
    if current_chunk:
        chunks.append(current_chunk)
    
    # Send each chunk
    try:
        for chunk in chunks:
            response = requests.post(
                webhook_url,
                json={'content': chunk},
                timeout=10
            )
            if response.status_code != 204:
                print(f"   ⚠ Discord returned {response.status_code}")
        
        print(f"   ✓ Discord notification sent")
        
    except Exception as e:
        print(f"   ⚠ Discord error: {e}")

if __name__ == '__main__':
    # Test notification with dummy job
    test_jobs = [{
        'id': 'test_123',
        'title': 'Senior Grants Manager',
        'agency': 'Test Agency',
        'location': 'Baltimore, MD',
        'url': 'https://example.com/job',
        'salary': '$85,000 - $110,000',
        'posted': '2025-01-12',
        'source': 'USAJobs'
    }]
    
    print("Testing email notification...")
    send_email_notification(test_jobs)
